### ISSUE TITLE
Compatibility with IE9

### ISSUE THREAD

**Issue by Andreioli** [christabor/css-progress-wizard#1]
there is a hack to fix this error?
![ieerro](https://cloud.githubusercontent.com/assets/1133390/8211486/6efa90ea-14ed-11e5-9b43-7b08f0223adf.PNG)

ps: IE9

Thanks.

**Comment by spoland** [comment]
My hack to fix on IE9:

```
<!--[if ie 9]>
    <style>
        .progress-indicator > li {
            width: 20%;
            margin: -2px;
            display: inline-block;
        }
        .progress-indicator {
            padding-left: 10px;
        }
    </style>
<![endif]-->
```

**Comment by christabor** [comment]
IE9 Doesn't have support for flexbox I believe, but you could shim it, or use a polyfill. Check this out: https://github.com/doctyper/flexie
