### ISSUE TITLE
MIT License? 

### ISSUE THREAD

**Issue by httpete** [christabor/css-progress-wizard#11]
Hi, can you release this under MIT As well?

**Comment by christabor** [comment]
Done.

**Comment by httpete** [comment]
Thanks!I was going to sit down and build a flexbox / sass progress wizard and through the magic of google found your perfect solution! I am allergic to bootstrap positioning classes and yours is perfecto. Thanks!

**Comment by christabor** [comment]
I'm glad to hear it, that's great!
