### ISSUE TITLE
Release via NPM

### ISSUE THREAD

**Issue by httpete** [christabor/css-progress-wizard#15]
Hi,

another project has forked this and changed it to GPL-3. I need this under MIT. Can you publish this to npm or can we get the other project to change to MIT as this one does? Thank you.

**Comment by christabor** [comment]
Which one is that? I can publish it to npm.

**Comment by httpete** [comment]
https://www.npmjs.com/package/css-progress-wizard

Forked from you but is gpl. You had mit. Would you publish under a diff name? Thanks - do you have a donation link?

**Comment by christabor** [comment]
@httpete https://www.npmjs.com/package/css_progress_wizard is now up, closing. Thanks!

**Comment by httpete** [comment]
Chris thank you kindly for the speedy fix. I am back in business!

**Comment by christabor** [comment]
👍
