### ISSUE TITLE
Can you remove the bower.json file from the old project which has lgpl in it?

### ISSUE THREAD

**Issue by httpete** [christabor/css-progress-wizard#18]

**Comment by christabor** [comment]
Done in https://github.com/christabor/css-progress-wizard/commit/85aff57d45e8293d4fd6625f377bc52283b60cc2

**Comment by httpete** [comment]
chris, are you going to publish this to css_progress_wizard (note the _) in npm? That is how we consume the MIT packaged version. Thank you very much

**Comment by christabor** [comment]
Ah, good call; thanks for the reminder. I'll reopen until that's done

**Comment by christabor** [comment]
See https://www.npmjs.com/package/css_progress_wizard
