### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by halaei** [christabor/css-progress-wizard#5]
Could you please npm publish this package?

**Comment by christabor** [comment]
Isn't NPM for node packages? This contains no javascript.

**Comment by halaei** [comment]
It can be used for front-end dependency management as well. For example, we use gulp and elixir in our Laravel projects. Our gulpfile compiles sass and less, copies and merges and minifies css files and js files (_many obtained from node_modules directory_), version the final files to prevent out-dated files being cached client side and so on.

**Comment by halaei** [comment]
I made something for myself. Thanks anyway.
